window.heros = [
    {
        "name": "Aradel",
        "link": "https://rivengard.fandom.com/wiki/Aradel",
        "img": "Aradel.webp",
        "rarity": "Rare",
        "affinity": "Blue",
        "class": "Mage",
        "faction": "Azure Tower",
        "traits": "Ranged",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 3,
        "hp": 25,
        "hp_max": 2131,
        "damage": 16,
        "damage_max": 1477,
        "armor": 16,
        "armor_max": 1353,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Coryn",
        "link": "https://rivengard.fandom.com/wiki/Coryn",
        "img": "Coryn.webp",
        "rarity": "Common",
        "affinity": "Blue",
        "class": "Warrior",
        "faction": "Azure Tower",
        "traits": "Flying,Elemental",
        "damage_type": "Magical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "hp": 38,
        "hp_max": 3936,
        "damage": 16,
        "damage_max": 1648,
        "armor": 25,
        "armor_max": 2579,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Naevys",
        "link": "https://rivengard.fandom.com/wiki/Naevys",
        "img": "Naevys.webp",
        "rarity": "Common",
        "affinity": "Blue",
        "class": "Rogue",
        "faction": "Azure Tower",
        "traits": "Polearm",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "hp": 40,
        "hp_max": 3996,
        "damage": 17,
        "damage_max": 1702,
        "armor": 16,
        "armor_max": 1600,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Pendar",
        "link": "https://rivengard.fandom.com/wiki/Pendar",
        "img": "Pendar.webp",
        "rarity": "Uncommon",
        "affinity": "Blue",
        "class": "Mage",
        "faction": "Azure Tower",
        "traits": "Ranged",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "hp": 30,
        "hp_max": 3123,
        "damage": 18,
        "damage_max": 1852,
        "armor": 15,
        "armor_max": 1558,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Zefa",
        "link": "https://rivengard.fandom.com/wiki/Zefa",
        "img": "Zefa.webp",
        "rarity": "Uncommon",
        "affinity": "Blue",
        "class": "Warrior",
        "faction": "Azure Tower",
        "traits": "Hulking,Elemental",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "hp": 63,
        "hp_max": 6214,
        "damage": 12,
        "damage_max": 1196,
        "armor": 20,
        "armor_max": 2000,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Shield"
    },
    {
        "name": "Agnar",
        "link": "https://rivengard.fandom.com/wiki/Agnar",
        "img": "Agnar.webp",
        "rarity": "Epic",
        "affinity": "Red",
        "class": "Warrior",
        "faction": "Blazing Brew",
        "traits": "Inebriated",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 2,
        "hp": 63,
        "hp_max": 5324,
        "damage": 10,
        "damage_max": 838,
        "armor": 61,
        "armor_max": 5107,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Balmur",
        "link": "https://rivengard.fandom.com/wiki/Balmur",
        "img": "Balmur.webp",
        "rarity": "Rare",
        "affinity": "Red",
        "class": "Mage",
        "faction": "Blazing Brew",
        "traits": "Inebriated,Ranged",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 2,
        "hp": 35,
        "hp_max": 3267,
        "damage": 14,
        "damage_max": 1308,
        "armor": 35,
        "armor_max": 3276,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "name": "Cinder",
        "link": "https://rivengard.fandom.com/wiki/Cinder",
        "img": "Cinder.webp",
        "rarity": "Common",
        "affinity": "Red",
        "class": "Warrior",
        "faction": "Blazing Brew",
        "traits": "Inebriated,Mechanic",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 2,
        "hp": 57,
        "hp_max": 5721,
        "damage": 13,
        "damage_max": 1305,
        "armor": 57,
        "armor_max": 5731,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Salvo",
        "link": "https://rivengard.fandom.com/wiki/Salvo",
        "img": "Salvo.webp",
        "rarity": "Rare",
        "affinity": "Red",
        "class": "Rogue",
        "faction": "Blazing Brew",
        "traits": "Inebriated,Ranged",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 2,
        "hp": 27,
        "hp_max": 2966,
        "damage": 12,
        "damage_max": 1321,
        "armor": 13,
        "armor_max": 1430,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Sunshine",
        "link": "https://rivengard.fandom.com/wiki/Sunshine",
        "img": "Sunshine.webp",
        "rarity": "Uncommon",
        "affinity": "Red",
        "class": "Rogue",
        "faction": "Blazing Brew",
        "traits": "Flying,Mechanical,Dragon Scales",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "hp": 35,
        "hp_max": 3142,
        "damage": 16,
        "damage_max": 1440,
        "armor": 15,
        "armor_max": 1350,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "name": "Aceshru",
        "link": "https://rivengard.fandom.com/wiki/Aceshru",
        "img": "Aceshru.webp",
        "rarity": "Uncommon",
        "affinity": "Dark",
        "class": "Mage",
        "faction": "Cavern Realm",
        "traits": "Night Vision,Ranged",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 3,
        "hp": 30,
        "hp_max": 2604,
        "damage": 14,
        "damage_max": 1216,
        "armor": 9,
        "armor_max": 780,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Nimrul",
        "link": "https://rivengard.fandom.com/wiki/Nimrul",
        "img": "Nimrul.webp",
        "rarity": "Rare",
        "affinity": "Dark",
        "class": "Rogue",
        "faction": "Cavern Realm",
        "traits": "Night Vision",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "hp": 40,
        "hp_max": 3148,
        "damage": 18,
        "damage_max": 1420,
        "armor": 13,
        "armor_max": 1024,
        "slot1": "Weapon",
        "slot2": "Weapon",
        "slot3": "Ring"
    },
    {
        "name": "Ranaklu",
        "link": "https://rivengard.fandom.com/wiki/Ranaklu",
        "img": "Ranaklu.webp",
        "rarity": "Common",
        "affinity": "Dark",
        "class": "Mage",
        "faction": "Cavern Realm",
        "traits": "Night Vision,Shadewalker,Terrifying",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "hp": 39,
        "hp_max": 3878,
        "damage": 13,
        "damage_max": 1289,
        "armor": 18,
        "armor_max": 1785,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Umanu",
        "link": "https://rivengard.fandom.com/wiki/Umanu",
        "img": "Umanu.webp",
        "rarity": "Common",
        "affinity": "Dark",
        "class": "Rogue",
        "faction": "Cavern Realm",
        "traits": "Night Vision,Ranged",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 2,
        "movement": 3,
        "hp": 38,
        "hp_max": 3849,
        "damage": 15,
        "damage_max": 1513,
        "armor": 10,
        "armor_max": 1011,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Voyassa",
        "link": "https://rivengard.fandom.com/wiki/Voyassa",
        "img": "Voyassa.webp",
        "rarity": "Common",
        "affinity": "Dark",
        "class": "Warrior",
        "faction": "Cavern Realm",
        "traits": "Night Vision,Mounted",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "hp": 60,
        "hp_max": 6041,
        "damage": 11,
        "damage_max": 1113,
        "armor": 35,
        "armor_max": 3542,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Contorta",
        "link": "https://rivengard.fandom.com/wiki/Contorta",
        "img": "Contorta.webp",
        "rarity": "Uncommon",
        "affinity": "Light",
        "class": "Rogue",
        "faction": "Fiveport",
        "traits": "n/a",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "hp": 0,
        "hp_max": 3123,
        "damage": 0,
        "damage_max": 1590,
        "armor": 0,
        "armor_max": 1302,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Freneric",
        "link": "https://rivengard.fandom.com/wiki/Freneric",
        "img": "Freneric.webp",
        "rarity": "Uncommon",
        "affinity": "Light",
        "class": "Mage",
        "faction": "Fiveport",
        "traits": "Sturdy,Ranged",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 2,
        "hp": 0,
        "hp_max": 4352,
        "damage": 0,
        "damage_max": 1171,
        "armor": 0,
        "armor_max": 2448,
        "slot1": "Armor",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "name": "Ignozio",
        "link": "https://rivengard.fandom.com/wiki/Ignozio",
        "img": "Ignozio.webp",
        "rarity": "Uncommon",
        "affinity": "Light",
        "class": "Rogue",
        "faction": "Fiveport",
        "traits": "Ranged",
        "damage_type": "Magical",
        "armor_type": "Physical",
        "range": 3,
        "movement": 2,
        "hp": 42,
        "hp_max": 2729,
        "damage": 22,
        "damage_max": 1299,
        "armor": 42,
        "armor_max": 1856,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Lucente III",
        "link": "https://rivengard.fandom.com/wiki/Lucente_III",
        "img": "Lucente_III.webp",
        "rarity": "Common",
        "affinity": "Light",
        "class": "Mage",
        "faction": "Fiveport",
        "traits": "Fear of Death,Healer,Ranged",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "hp": 30,
        "hp_max": 3123,
        "damage": 18,
        "damage_max": 1852,
        "armor": 15,
        "armor_max": 1555,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Vittoria",
        "link": "https://rivengard.fandom.com/wiki/Vittoria",
        "img": "Vittoria.webp",
        "rarity": "Common",
        "affinity": "Light",
        "class": "Warrior",
        "faction": "Fiveport",
        "traits": "Inebriated,Looter",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "hp": 50,
        "hp_max": 4393,
        "damage": 15,
        "damage_max": 1673,
        "armor": 40,
        "armor_max": 2246,
        "slot1": "Weapon",
        "slot2": "Weapon",
        "slot3": "Ring"
    },
    {
        "name": "Areus",
        "link": "https://rivengard.fandom.com/wiki/Areus",
        "img": "Areus.webp",
        "rarity": "Common",
        "affinity": "Light",
        "class": "Mage",
        "faction": "Radiant Order",
        "traits": "Ranged",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "hp": 32,
        "hp_max": 3040,
        "damage": 16,
        "damage_max": 1523,
        "armor": 0,
        "armor_max": 940,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Hanna",
        "link": "https://rivengard.fandom.com/wiki/Hanna",
        "img": "Hanna.webp",
        "rarity": "Common",
        "affinity": "Light",
        "class": "Mage",
        "faction": "Radiant Order",
        "traits": "Healer,Ranged",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "hp": 40,
        "hp_max": 4006,
        "damage": 13,
        "damage_max": 1299,
        "armor": 0,
        "armor_max": 1225,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Monty",
        "link": "https://rivengard.fandom.com/wiki/Monty",
        "img": "Monty.webp",
        "rarity": "Common",
        "affinity": "Light",
        "class": "Rogue",
        "faction": "Radiant Order",
        "traits": "Ranged",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 2,
        "hp": 35,
        "hp_max": 3433,
        "damage": 15,
        "damage_max": 1475,
        "armor": 0,
        "armor_max": 1411,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Sigrid",
        "link": "https://rivengard.fandom.com/wiki/Sigrid",
        "img": "Sigrid.webp",
        "rarity": "Common",
        "affinity": "Light",
        "class": "Warrior",
        "faction": "Radiant Order",
        "traits": "n/a",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "hp": 50,
        "hp_max": 5190,
        "damage": 14,
        "damage_max": 1449,
        "armor": 0,
        "armor_max": 1881,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Sir Matteus",
        "link": "https://rivengard.fandom.com/wiki/Sir_Matteus",
        "img": "Matteus.webp",
        "rarity": "Common",
        "affinity": "Light",
        "class": "Warrior",
        "faction": "Radiant Order",
        "traits": "Mounted",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "hp": 58,
        "hp_max": 5356,
        "damage": 10,
        "damage_max": 928,
        "armor": 0,
        "armor_max": 3289,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "name": "Bullmon",
        "link": "https://rivengard.fandom.com/wiki/Bullmon",
        "img": "Bullmon.webp",
        "rarity": "Rare",
        "affinity": "Blue",
        "class": "Warrior",
        "faction": "Reefkin",
        "traits": "Hulking,Ranged",
        "damage_type": "Magical",
        "armor_type": "Physical",
        "range": 3,
        "movement": 2,
        "hp": 40,
        "hp_max": 3308,
        "damage": 14,
        "damage_max": 1161,
        "armor": 11,
        "armor_max": 908,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Dorga",
        "link": "https://rivengard.fandom.com/wiki/Dorga",
        "img": "Dorga.webp",
        "rarity": "Legendary",
        "affinity": "Blue",
        "class": "Mage",
        "faction": "Reefkin",
        "traits": "Amphibious",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "hp": 40,
        "hp_max": 3164,
        "damage": 17,
        "damage_max": 1337,
        "armor": 20,
        "armor_max": 1587,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Gix",
        "link": "https://rivengard.fandom.com/wiki/Gix",
        "img": "Gix.webp",
        "rarity": "Uncommon",
        "affinity": "Blue",
        "class": "Rogue",
        "faction": "Reefkin",
        "traits": "Ranged,Amphibious",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "hp": 33,
        "hp_max": 2809,
        "damage": 14,
        "damage_max": 1196,
        "armor": 12,
        "armor_max": 1020,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Timtim",
        "link": "https://rivengard.fandom.com/wiki/Timtim",
        "img": "Timtim.webp",
        "rarity": "Epic",
        "affinity": "Blue",
        "class": "Mage",
        "faction": "Reefkin",
        "traits": "Mounted,Ranged",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 3,
        "hp": 28,
        "hp_max": 2188,
        "damage": 15,
        "damage_max": 1168,
        "armor": 10,
        "armor_max": 780,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Tokon",
        "link": "https://rivengard.fandom.com/wiki/Tokon",
        "img": "Tokon.webp",
        "rarity": "Common",
        "affinity": "Blue",
        "class": "Warrior",
        "faction": "Reefkin",
        "traits": "Polearm,Amphibious",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "hp": 60,
        "hp_max": 6310,
        "damage": 11,
        "damage_max": 1145,
        "armor": 46,
        "armor_max": 4796,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "name": "Boulder",
        "link": "https://rivengard.fandom.com/wiki/Boulder",
        "img": "Boulder.webp",
        "rarity": "Common",
        "affinity": "Green",
        "class": "Warrior",
        "faction": "Rinji Dynasty",
        "traits": "Hulking",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "hp": 65,
        "hp_max": 6566,
        "damage": 13,
        "damage_max": 1302,
        "armor": 45,
        "armor_max": 4355,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "name": "Gibbo & Gobbo",
        "link": "https://rivengard.fandom.com/wiki/Gibbo_%26_Gobbo",
        "img": "GibboGobbo.webp",
        "rarity": "Common",
        "affinity": "Green",
        "class": "Rogue",
        "faction": "Rinji Dynasty",
        "traits": "Polearm",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "hp": 44,
        "hp_max": 4374,
        "damage": 17,
        "damage_max": 1680,
        "armor": 22,
        "armor_max": 2188,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Pari",
        "link": "https://rivengard.fandom.com/wiki/Pari",
        "img": "Pari.webp",
        "rarity": "Common",
        "affinity": "Green",
        "class": "Rogue",
        "faction": "Rinji Dynasty",
        "traits": "Ranged",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "hp": 38,
        "hp_max": 3223,
        "damage": 14,
        "damage_max": 1446,
        "armor": 14,
        "armor_max": 1440,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "name": "Sir Florianus",
        "link": "https://rivengard.fandom.com/wiki/Sir_Florianus",
        "img": "Florianus.webp",
        "rarity": "Common",
        "affinity": "Green",
        "class": "Warrior",
        "faction": "Rinji Dynasty",
        "traits": "Mounted",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "hp": 42,
        "hp_max": 4156,
        "damage": 15,
        "damage_max": 1475,
        "armor": 18,
        "armor_max": 1779,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Tawa Rinji",
        "link": "https://rivengard.fandom.com/wiki/Tawa_Rinji",
        "img": "TawaRinji.webp",
        "rarity": "Uncommon",
        "affinity": "Green",
        "class": "Mage",
        "faction": "Rinji Dynasty",
        "traits": "Healer,Ranged",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 2,
        "hp": 33,
        "hp_max": 2859,
        "damage": 12,
        "damage_max": 1052,
        "armor": 10,
        "armor_max": 880,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Cervidus",
        "link": "https://rivengard.fandom.com/wiki/Cervidus",
        "img": "Cervidus.webp",
        "rarity": "Common",
        "affinity": "Green",
        "class": "Mage",
        "faction": "Sacred Grove",
        "traits": "Ranged,Bushkin",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "hp": 45,
        "hp_max": 4477,
        "damage": 12,
        "damage_max": 1161,
        "armor": 25,
        "armor_max": 2432,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Nixie",
        "link": "https://rivengard.fandom.com/wiki/Nixie",
        "img": "Nixie.webp",
        "rarity": "Common",
        "affinity": "Green",
        "class": "Mage",
        "faction": "Sacred Grove",
        "traits": "Healer,Ranged,Bushkin",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 3,
        "hp": 25,
        "hp_max": 2412,
        "damage": 16,
        "damage_max": 1545,
        "armor": 16,
        "armor_max": 1548,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Oakenshrub",
        "link": "https://rivengard.fandom.com/wiki/Oakenshrub",
        "img": "Oakenshrub.webp",
        "rarity": "Uncommon",
        "affinity": "Green",
        "class": "Warrior",
        "faction": "Sacred Grove",
        "traits": "Bushkin,Elemental",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "hp": 70,
        "hp_max": 6684,
        "damage": 9,
        "damage_max": 848,
        "armor": 60,
        "armor_max": 5692,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Scruffy",
        "link": "https://rivengard.fandom.com/wiki/Scruffy",
        "img": "Scruffy.webp",
        "rarity": "Common",
        "affinity": "Green",
        "class": "Rogue",
        "faction": "Sacred Grove",
        "traits": "Bushkin",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "hp": 40,
        "hp_max": 3884,
        "damage": 19,
        "damage_max": 1843,
        "armor": 30,
        "armor_max": 2889,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Silverroot",
        "link": "https://rivengard.fandom.com/wiki/Silverroot",
        "img": "Silverroot.webp",
        "rarity": "Uncommon",
        "affinity": "Green",
        "class": "Warrior",
        "faction": "Sacred Grove",
        "traits": "Mounted,Bushkin",
        "damage_type": "Magical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "hp": 40,
        "hp_max": 3507,
        "damage": 14,
        "damage_max": 1232,
        "armor": 11,
        "armor_max": 963,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Ardasi",
        "link": "https://rivengard.fandom.com/wiki/Ardasi",
        "img": "Ardasi.webp",
        "rarity": "Rare",
        "affinity": "Light",
        "class": "Mage",
        "faction": "Shara'Zar Traders",
        "traits": "Ranged",
        "damage_type": "Magical",
        "armor_type": "Universal",
        "range": 3,
        "movement": 2,
        "hp": 31,
        "hp_max": 3200,
        "damage": 15,
        "damage_max": 1545,
        "armor": 20,
        "armor_max": 2070,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Harun",
        "link": "https://rivengard.fandom.com/wiki/Harun",
        "img": "Harun.webp",
        "rarity": "Uncommon",
        "affinity": "Light",
        "class": "Warrior",
        "faction": "Shara'Zar Traders",
        "traits": "Mounted,Burrow",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "hp": 32,
        "hp_max": 3332,
        "damage": 15,
        "damage_max": 1571,
        "armor": 12,
        "armor_max": 1254,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Thana Moh",
        "link": "https://rivengard.fandom.com/wiki/Thana_Moh",
        "img": "ThanaMoh.webp",
        "rarity": "Epic",
        "affinity": "Light",
        "class": "Rogue",
        "faction": "Shara'Zar Traders",
        "traits": "Flying",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "hp": 35,
        "hp_max": 2880,
        "damage": 19,
        "damage_max": 1564,
        "armor": 10,
        "armor_max": 822,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Yasamin",
        "link": "https://rivengard.fandom.com/wiki/Yasamin",
        "img": "Yasamin.webp",
        "rarity": "Uncommon",
        "affinity": "Light",
        "class": "Warrior",
        "faction": "Shara'Zar Traders",
        "traits": "Mounted,Hulking,Looter",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "hp": 55,
        "hp_max": 5363,
        "damage": 11,
        "damage_max": 1075,
        "armor": 40,
        "armor_max": 3910,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Ziyad",
        "link": "https://rivengard.fandom.com/wiki/Ziyad",
        "img": "Ziyad.webp",
        "rarity": "Rare",
        "affinity": "Light",
        "class": "Mage",
        "faction": "Shara'Zar Traders",
        "traits": "n/a",
        "damage_type": "Magical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "hp": 40,
        "hp_max": 3676,
        "damage": 17,
        "damage_max": 1574,
        "armor": 21,
        "armor_max": 1939,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Buzzy Klonkson",
        "link": "https://rivengard.fandom.com/wiki/Buzzy_Klonkson",
        "img": "Polish_20220525_162737370.webp",
        "rarity": "Uncommon",
        "affinity": "Red",
        "class": "Warrior",
        "faction": "The Hive",
        "traits": "Hulking,Mechanical,Looter",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "hp": 0,
        "hp_max": 6694,
        "damage": 0,
        "damage_max": 768,
        "armor": 0,
        "armor_max": 5699,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Snazzbang",
        "link": "https://rivengard.fandom.com/wiki/Snazzbang",
        "img": "Snazzbang_Transparent.webp",
        "rarity": "Uncommon",
        "affinity": "Red",
        "class": "Rogue",
        "faction": "The Hive",
        "traits": "Magic Resistance,Mechanic,Ranged",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 2,
        "hp": 49,
        "hp_max": 3443,
        "damage": 22,
        "damage_max": 1296,
        "armor": 21,
        "armor_max": 1292,
        "slot1": "Weapon",
        "slot2": "Weapon",
        "slot3": "Ring"
    },
    {
        "name": "Sprocket",
        "link": "https://rivengard.fandom.com/wiki/Sprocket",
        "img": "Screenshot_20220524-101132_Rivengard.webp",
        "rarity": "Uncommon",
        "affinity": "Red",
        "class": "Rogue",
        "faction": "The Hive",
        "traits": "Magic Resistance,Mechanic",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "hp": 63,
        "hp_max": 4537,
        "damage": 19,
        "damage_max": 1417,
        "armor": 63,
        "armor_max": 4566,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Staticrackle",
        "link": "https://rivengard.fandom.com/wiki/Staticrackle",
        "img": "Staticrackle.webp",
        "rarity": "Uncommon",
        "affinity": "Red",
        "class": "Rogue",
        "faction": "The Hive",
        "traits": "Magic Resistance,Mechanic,Ranged",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 2,
        "hp": 51,
        "hp_max": 2748,
        "damage": 19,
        "damage_max": 1257,
        "armor": 19,
        "armor_max": 1174,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Wingtip",
        "link": "https://rivengard.fandom.com/wiki/Wingtip",
        "img": "Polish_20220621_220939307.webp",
        "rarity": "Uncommon",
        "affinity": "Red",
        "class": "Warrior",
        "faction": "The Hive",
        "traits": "Magic Resistance,Flying",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "hp": 44,
        "hp_max": 3344,
        "damage": 21,
        "damage_max": 1571,
        "armor": 16,
        "armor_max": 1254,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Caradan",
        "link": "https://rivengard.fandom.com/wiki/Caradan",
        "img": "Caradan.webp",
        "rarity": "Common",
        "affinity": "Red",
        "class": "Mage",
        "faction": "Walled Kingdoms",
        "traits": "Ranged",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "hp": 35,
        "hp_max": 3289,
        "damage": 14,
        "damage_max": 1315,
        "armor": 15,
        "armor_max": 1408,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Lyonette",
        "link": "https://rivengard.fandom.com/wiki/Lyonette",
        "img": "Lyonette.webp",
        "rarity": "Common",
        "affinity": "Red",
        "class": "Warrior",
        "faction": "Walled Kingdoms",
        "traits": "Mounted",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "hp": 38,
        "hp_max": 3856,
        "damage": 15,
        "damage_max": 1520,
        "armor": 20,
        "armor_max": 2025,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Mivera",
        "link": "https://rivengard.fandom.com/wiki/Mivera",
        "img": "Mivera.webp",
        "rarity": "Common",
        "affinity": "Red",
        "class": "Rogue",
        "faction": "Walled Kingdoms",
        "traits": "Ranged,Fear of Death",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 3,
        "hp": 25,
        "hp_max": 2460,
        "damage": 15,
        "damage_max": 1472,
        "armor": 10,
        "armor_max": 985,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Pelator",
        "link": "https://rivengard.fandom.com/wiki/Pelator",
        "img": "Pelator.webp",
        "rarity": "Common",
        "affinity": "Red",
        "class": "Mage",
        "faction": "Walled Kingdoms",
        "traits": "Polearm",
        "damage_type": "Magical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "hp": 45,
        "hp_max": 4566,
        "damage": 15,
        "damage_max": 1520,
        "armor": 45,
        "armor_max": 4576,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "The Red Rat",
        "link": "https://rivengard.fandom.com/wiki/The_Red_Rat",
        "img": "RedRat.webp",
        "rarity": "Common",
        "affinity": "Red",
        "class": "Warrior",
        "faction": "Walled Kingdoms",
        "traits": "Eager,Hulking",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "hp": 65,
        "hp_max": 6656,
        "damage": 10,
        "damage_max": 1017,
        "armor": 65,
        "armor_max": 6435,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Akio",
        "link": "https://rivengard.fandom.com/wiki/Akio",
        "img": "Akio.webp",
        "rarity": "Rare",
        "affinity": "Dark",
        "class": "Warrior",
        "faction": "Waning Moon",
        "traits": "Mounted",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "hp": 50,
        "hp_max": 4134,
        "damage": 12,
        "damage_max": 988,
        "armor": 33,
        "armor_max": 2745,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "name": "Grandma Bones",
        "link": "https://rivengard.fandom.com/wiki/Grandma_Bones",
        "img": "GmaBones.webp",
        "rarity": "Legendary",
        "affinity": "Dark",
        "class": "Mage",
        "faction": "Waning Moon",
        "traits": "Ranged",
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "hp": 30,
        "hp_max": 2393,
        "damage": 16,
        "damage_max": 1283,
        "armor": 9,
        "armor_max": 723,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Katsume",
        "link": "https://rivengard.fandom.com/wiki/Katsume",
        "img": "Katsume.webp",
        "rarity": "Uncommon",
        "affinity": "Dark",
        "class": "Rogue",
        "faction": "Waning Moon",
        "traits": "Ranged",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 2,
        "hp": 33,
        "hp_max": 3171,
        "damage": 15,
        "damage_max": 1440,
        "armor": 13,
        "armor_max": 1254,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Shun",
        "link": "https://rivengard.fandom.com/wiki/Shun",
        "img": "Shun.webp",
        "rarity": "Uncommon",
        "affinity": "Dark",
        "class": "Rogue",
        "faction": "Waning Moon",
        "traits": "n/a",
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "hp": 42,
        "hp_max": 3968,
        "damage": 18,
        "damage_max": 1689,
        "armor": 22,
        "armor_max": 2076,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "name": "Taro",
        "link": "https://rivengard.fandom.com/wiki/Taro",
        "img": "Taro.webp",
        "rarity": "Common",
        "affinity": "Dark",
        "class": "Warrior",
        "faction": "Waning Moon",
        "traits": "Polearm",
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "hp": 65,
        "hp_max": 6246,
        "damage": 11,
        "damage_max": 1075,
        "armor": 41,
        "armor_max": 4019,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    }
]