window.heros = [
    {
        "link": "https://rivengard.fandom.com/wiki/Aceshru",
        "img": "Aceshru.webp",
        "name": "Aceshru",
        "rarity": "Uncommon",
        "affinity": "Dark",
        "class": "Mage",
        "faction": "Cavern Realm",
        "traits": [
            "Night Vision",
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 3,
        "health": 30,
        "damage": 14,
        "armor": 9,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Buzzy_Klonkson",
        "img": "Polish_20220525_162737370.webp",
        "name": "Buzzy Klonkson",
        "rarity": "Uncommon",
        "affinity": "Red",
        "class": "Warrior",
        "faction": "The Hive",
        "traits": [
            "Hulking",
            "Mechanical",
            "Looter"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "health": 0,
        "damage": 0,
        "armor": 0,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Contorta",
        "img": "Contorta.webp",
        "name": "Contorta",
        "rarity": "Uncommon",
        "affinity": "Light",
        "class": "Rogue",
        "faction": "Fiveport",
        "traits": [
            "n/a"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "health": 0,
        "damage": 0,
        "armor": 0,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Freneric",
        "img": "Freneric.webp",
        "name": "Freneric",
        "rarity": "Uncommon",
        "affinity": "Light",
        "class": "Mage",
        "faction": "Fiveport",
        "traits": [
            "Sturdy",
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 2,
        "health": 0,
        "damage": 0,
        "armor": 0,
        "slot1": "Armor",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Gix",
        "img": "Gix.webp",
        "name": "Gix",
        "rarity": "Uncommon",
        "affinity": "Blue",
        "class": "Rogue",
        "faction": "Reefkin",
        "traits": [
            "Ranged",
            "Amphibious"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "health": 33,
        "damage": 14,
        "armor": 12,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Harun",
        "img": "Harun.webp",
        "name": "Harun",
        "rarity": "Uncommon",
        "affinity": "Light",
        "class": "Warrior",
        "faction": "Shara'Zar Traders",
        "traits": [
            "Mounted",
            "Burrow"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "health": 32,
        "damage": 15,
        "armor": 12,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Ignozio",
        "img": "Ignozio.webp",
        "name": "Ignozio",
        "rarity": "Uncommon",
        "affinity": "Light",
        "class": "Rogue",
        "faction": "Fiveport",
        "traits": [
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Physical",
        "range": 3,
        "movement": 2,
        "health": 42,
        "damage": 22,
        "armor": 42,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Katsume",
        "img": "Katsume.webp",
        "name": "Katsume",
        "rarity": "Uncommon",
        "affinity": "Dark",
        "class": "Rogue",
        "faction": "Waning Moon",
        "traits": [
            "Ranged"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 2,
        "health": 33,
        "damage": 15,
        "armor": 13,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Oakenshrub",
        "img": "Oakenshrub.webp",
        "name": "Oakenshrub",
        "rarity": "Uncommon",
        "affinity": "Green",
        "class": "Warrior",
        "faction": "Sacred Grove",
        "traits": [
            "Bushkin",
            "Elemental"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "health": 70,
        "damage": 9,
        "armor": 60,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Pendar",
        "img": "Pendar.webp",
        "name": "Pendar",
        "rarity": "Uncommon",
        "affinity": "Blue",
        "class": "Mage",
        "faction": "Azure Tower",
        "traits": [
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "health": 30,
        "damage": 18,
        "armor": 15,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Shun",
        "img": "Shun.webp",
        "name": "Shun",
        "rarity": "Uncommon",
        "affinity": "Dark",
        "class": "Rogue",
        "faction": "Waning Moon",
        "traits": [
            "n/a"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "health": 42,
        "damage": 18,
        "armor": 22,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Silverroot",
        "img": "Silverroot.webp",
        "name": "Silverroot",
        "rarity": "Uncommon",
        "affinity": "Green",
        "class": "Warrior",
        "faction": "Sacred Grove",
        "traits": [
            "Mounted",
            "Bushkin"
        ],
        "damage_type": "Magical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "health": 40,
        "damage": 14,
        "armor": 11,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Snazzbang",
        "img": "Snazzbang_Transparent.webp",
        "name": "Snazzbang",
        "rarity": "Uncommon",
        "affinity": "Red",
        "class": "Rogue",
        "faction": "The Hive",
        "traits": [
            "Magic Resistance",
            "Mechanic",
            "Ranged"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 2,
        "health": 49,
        "damage": 22,
        "armor": 21,
        "slot1": "Weapon",
        "slot2": "Weapon",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Sprocket",
        "img": "Screenshot_20220524-101132_Rivengard.webp",
        "name": "Sprocket",
        "rarity": "Uncommon",
        "affinity": "Red",
        "class": "Rogue",
        "faction": "The Hive",
        "traits": [
            "Magic Resistance",
            "Mechanic"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "health": 63,
        "damage": 19,
        "armor": 63,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Staticrackle",
        "img": "Staticrackle.webp",
        "name": "Staticrackle",
        "rarity": "Uncommon",
        "affinity": "Red",
        "class": "Rogue",
        "faction": "The Hive",
        "traits": [
            "Magic Resistance",
            "Mechanic",
            "Ranged"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 2,
        "health": 51,
        "damage": 19,
        "armor": 19,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Sunshine",
        "img": "Sunshine.webp",
        "name": "Sunshine",
        "rarity": "Uncommon",
        "affinity": "Red",
        "class": "Rogue",
        "faction": "Blazing Brew",
        "traits": [
            "Flying",
            "Mechanical",
            "Dragon Scales"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "health": 35,
        "damage": 16,
        "armor": 15,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Tawa_Rinji",
        "img": "TawaRinji.webp",
        "name": "Tawa Rinji",
        "rarity": "Uncommon",
        "affinity": "Green",
        "class": "Mage",
        "faction": "Rinji Dynasty",
        "traits": [
            "Healer",
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 2,
        "health": 33,
        "damage": 12,
        "armor": 10,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Wingtip",
        "img": "Polish_20220621_220939307.webp",
        "name": "Wingtip",
        "rarity": "Uncommon",
        "affinity": "Red",
        "class": "Warrior",
        "faction": "The Hive",
        "traits": [
            "Magic Resistance",
            "Flying"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "health": 44,
        "damage": 21,
        "armor": 16,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Yasamin",
        "img": "Yasamin.webp",
        "name": "Yasamin",
        "rarity": "Uncommon",
        "affinity": "Light",
        "class": "Warrior",
        "faction": "Shara'Zar Traders",
        "traits": [
            "Mounted",
            "Hulking",
            "Looter"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "health": 55,
        "damage": 11,
        "armor": 40,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Zefa",
        "img": "Zefa.webp",
        "name": "Zefa",
        "rarity": "Uncommon",
        "affinity": "Blue",
        "class": "Warrior",
        "faction": "Azure Tower",
        "traits": [
            "Hulking",
            "Elemental"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "health": 63,
        "damage": 12,
        "armor": 20,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Shield"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Akio",
        "img": "Akio.webp",
        "name": "Akio",
        "rarity": "Rare",
        "affinity": "Dark",
        "class": "Warrior",
        "faction": "Waning Moon",
        "traits": [
            "Mounted"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "health": 50,
        "damage": 12,
        "armor": 33,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Aradel",
        "img": "Aradel.webp",
        "name": "Aradel",
        "rarity": "Rare",
        "affinity": "Blue",
        "class": "Mage",
        "faction": "Azure Tower",
        "traits": [
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 3,
        "health": 25,
        "damage": 16,
        "armor": 16,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Ardasi",
        "img": "Ardasi.webp",
        "name": "Ardasi",
        "rarity": "Rare",
        "affinity": "Light",
        "class": "Mage",
        "faction": "Shara'Zar Traders",
        "traits": [
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Universal",
        "range": 3,
        "movement": 2,
        "health": 31,
        "damage": 15,
        "armor": 20,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Balmur",
        "img": "Balmur.webp",
        "name": "Balmur",
        "rarity": "Rare",
        "affinity": "Red",
        "class": "Mage",
        "faction": "Blazing Brew",
        "traits": [
            "Inebriated",
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 2,
        "health": 35,
        "damage": 14,
        "armor": 35,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Bullmon",
        "img": "Bullmon.webp",
        "name": "Bullmon",
        "rarity": "Rare",
        "affinity": "Blue",
        "class": "Warrior",
        "faction": "Reefkin",
        "traits": [
            "Hulking",
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Physical",
        "range": 3,
        "movement": 2,
        "health": 40,
        "damage": 14,
        "armor": 11,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Nimrul",
        "img": "Nimrul.webp",
        "name": "Nimrul",
        "rarity": "Rare",
        "affinity": "Dark",
        "class": "Rogue",
        "faction": "Cavern Realm",
        "traits": [
            "Night Vision"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "health": 40,
        "damage": 18,
        "armor": 13,
        "slot1": "Weapon",
        "slot2": "Weapon",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Salvo",
        "img": "Salvo.webp",
        "name": "Salvo",
        "rarity": "Rare",
        "affinity": "Red",
        "class": "Rogue",
        "faction": "Blazing Brew",
        "traits": [
            "Inebriated",
            "Ranged"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 2,
        "health": 27,
        "damage": 12,
        "armor": 13,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Ziyad",
        "img": "Ziyad.webp",
        "name": "Ziyad",
        "rarity": "Rare",
        "affinity": "Light",
        "class": "Mage",
        "faction": "Shara'Zar Traders",
        "traits": [
            "n/a"
        ],
        "damage_type": "Magical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "health": 40,
        "damage": 17,
        "armor": 21,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Dorga",
        "img": "Dorga.webp",
        "name": "Dorga",
        "rarity": "Legendary",
        "affinity": "Blue",
        "class": "Mage",
        "faction": "Reefkin",
        "traits": [
            "Amphibious"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "health": 40,
        "damage": 17,
        "armor": 20,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Grandma_Bones",
        "img": "GmaBones.webp",
        "name": "Grandma Bones",
        "rarity": "Legendary",
        "affinity": "Dark",
        "class": "Mage",
        "faction": "Waning Moon",
        "traits": [
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "health": 30,
        "damage": 16,
        "armor": 9,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Agnar",
        "img": "Agnar.webp",
        "name": "Agnar",
        "rarity": "Epic",
        "affinity": "Red",
        "class": "Warrior",
        "faction": "Blazing Brew",
        "traits": [
            "Inebriated"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 2,
        "health": 63,
        "damage": 10,
        "armor": 61,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Thana_Moh",
        "img": "ThanaMoh.webp",
        "name": "Thana Moh",
        "rarity": "Epic",
        "affinity": "Light",
        "class": "Rogue",
        "faction": "Shara'Zar Traders",
        "traits": [
            "Flying"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "health": 35,
        "damage": 19,
        "armor": 10,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Timtim",
        "img": "Timtim.webp",
        "name": "Timtim",
        "rarity": "Epic",
        "affinity": "Blue",
        "class": "Mage",
        "faction": "Reefkin",
        "traits": [
            "Mounted",
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 3,
        "health": 28,
        "damage": 15,
        "armor": 10,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Areus",
        "img": "Areus.webp",
        "name": "Areus",
        "rarity": "Common",
        "affinity": "Light",
        "class": "Mage",
        "faction": "Radiant Order",
        "traits": [
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "health": 32,
        "damage": 16,
        "armor": 0,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Boulder",
        "img": "Boulder.webp",
        "name": "Boulder",
        "rarity": "Common",
        "affinity": "Green",
        "class": "Warrior",
        "faction": "Rinji Dynasty",
        "traits": [
            "Hulking"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "health": 65,
        "damage": 13,
        "armor": 45,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Caradan",
        "img": "Caradan.webp",
        "name": "Caradan",
        "rarity": "Common",
        "affinity": "Red",
        "class": "Mage",
        "faction": "Walled Kingdoms",
        "traits": [
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "health": 35,
        "damage": 14,
        "armor": 15,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Cinder",
        "img": "Cinder.webp",
        "name": "Cinder",
        "rarity": "Common",
        "affinity": "Red",
        "class": "Warrior",
        "faction": "Blazing Brew",
        "traits": [
            "Inebriated",
            "Mechanic"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 2,
        "health": 57,
        "damage": 13,
        "armor": 57,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Cervidus",
        "img": "Cervidus.webp",
        "name": "Cervidus",
        "rarity": "Common",
        "affinity": "Green",
        "class": "Mage",
        "faction": "Sacred Grove",
        "traits": [
            "Ranged",
            "Bushkin"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "health": 45,
        "damage": 12,
        "armor": 25,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Coryn",
        "img": "Coryn.webp",
        "name": "Coryn",
        "rarity": "Common",
        "affinity": "Blue",
        "class": "Warrior",
        "faction": "Azure Tower",
        "traits": [
            "Flying",
            "Elemental"
        ],
        "damage_type": "Magical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "health": 38,
        "damage": 16,
        "armor": 25,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Gibbo_%26_Gobbo",
        "img": "GibboGobbo.webp",
        "name": "Gibbo & Gobbo",
        "rarity": "Common",
        "affinity": "Green",
        "class": "Rogue",
        "faction": "Rinji Dynasty",
        "traits": [
            "Polearm"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "health": 44,
        "damage": 17,
        "armor": 22,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Hanna",
        "img": "Hanna.webp",
        "name": "Hanna",
        "rarity": "Common",
        "affinity": "Light",
        "class": "Mage",
        "faction": "Radiant Order",
        "traits": [
            "Healer",
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "health": 40,
        "damage": 13,
        "armor": 0,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Lucente_III",
        "img": "Lucente_III.webp",
        "name": "Lucente III",
        "rarity": "Common",
        "affinity": "Light",
        "class": "Mage",
        "faction": "Fiveport",
        "traits": [
            "Fear of Death",
            "Healer",
            "Ranged"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "health": 30,
        "damage": 18,
        "armor": 15,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Lyonette",
        "img": "Lyonette.webp",
        "name": "Lyonette",
        "rarity": "Common",
        "affinity": "Red",
        "class": "Warrior",
        "faction": "Walled Kingdoms",
        "traits": [
            "Mounted"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "health": 38,
        "damage": 15,
        "armor": 20,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Mivera",
        "img": "Mivera.webp",
        "name": "Mivera",
        "rarity": "Common",
        "affinity": "Red",
        "class": "Rogue",
        "faction": "Walled Kingdoms",
        "traits": [
            "Ranged",
            "Fear of Death"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 3,
        "health": 25,
        "damage": 15,
        "armor": 10,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Monty",
        "img": "Monty.webp",
        "name": "Monty",
        "rarity": "Common",
        "affinity": "Light",
        "class": "Rogue",
        "faction": "Radiant Order",
        "traits": [
            "Ranged"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 2,
        "health": 35,
        "damage": 15,
        "armor": 0,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Naevys",
        "img": "Naevys.webp",
        "name": "Naevys",
        "rarity": "Common",
        "affinity": "Blue",
        "class": "Rogue",
        "faction": "Azure Tower",
        "traits": [
            "Polearm"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "health": 40,
        "damage": 17,
        "armor": 16,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Nixie",
        "img": "Nixie.webp",
        "name": "Nixie",
        "rarity": "Common",
        "affinity": "Green",
        "class": "Mage",
        "faction": "Sacred Grove",
        "traits": [
            "Healer",
            "Ranged",
            "Bushkin"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 3,
        "movement": 3,
        "health": 25,
        "damage": 16,
        "armor": 16,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Pari",
        "img": "Pari.webp",
        "name": "Pari",
        "rarity": "Common",
        "affinity": "Green",
        "class": "Rogue",
        "faction": "Rinji Dynasty",
        "traits": [
            "Ranged"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 2,
        "movement": 3,
        "health": 38,
        "damage": 14,
        "armor": 14,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Pelator",
        "img": "Pelator.webp",
        "name": "Pelator",
        "rarity": "Common",
        "affinity": "Red",
        "class": "Mage",
        "faction": "Walled Kingdoms",
        "traits": [
            "Polearm"
        ],
        "damage_type": "Magical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "health": 45,
        "damage": 15,
        "armor": 45,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Ranaklu",
        "img": "Ranaklu.webp",
        "name": "Ranaklu",
        "rarity": "Common",
        "affinity": "Dark",
        "class": "Mage",
        "faction": "Cavern Realm",
        "traits": [
            "Night Vision",
            "Shadewalker",
            "Terrifying"
        ],
        "damage_type": "Magical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "health": 39,
        "damage": 13,
        "armor": 18,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Scruffy",
        "img": "Scruffy.webp",
        "name": "Scruffy",
        "rarity": "Common",
        "affinity": "Green",
        "class": "Rogue",
        "faction": "Sacred Grove",
        "traits": [
            "Bushkin"
        ],
        "damage_type": "Physical",
        "armor_type": "Magical",
        "range": 1,
        "movement": 3,
        "health": 40,
        "damage": 19,
        "armor": 30,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Sigrid",
        "img": "Sigrid.webp",
        "name": "Sigrid",
        "rarity": "Common",
        "affinity": "Light",
        "class": "Warrior",
        "faction": "Radiant Order",
        "traits": [
            "n/a"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "health": 50,
        "damage": 14,
        "armor": 0,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Sir_Florianus",
        "img": "Florianus.webp",
        "name": "Sir Florianus",
        "rarity": "Common",
        "affinity": "Green",
        "class": "Warrior",
        "faction": "Rinji Dynasty",
        "traits": [
            "Mounted"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "health": 42,
        "damage": 15,
        "armor": 18,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Sir_Matteus",
        "img": "Matteus.webp",
        "name": "Sir Matteus",
        "rarity": "Common",
        "affinity": "Light",
        "class": "Warrior",
        "faction": "Radiant Order",
        "traits": [
            "Mounted"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "health": 58,
        "damage": 10,
        "armor": 0,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Taro",
        "img": "Taro.webp",
        "name": "Taro",
        "rarity": "Common",
        "affinity": "Dark",
        "class": "Warrior",
        "faction": "Waning Moon",
        "traits": [
            "Polearm"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "health": 65,
        "damage": 11,
        "armor": 41,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/The_Red_Rat",
        "img": "RedRat.webp",
        "name": "The Red Rat",
        "rarity": "Common",
        "affinity": "Red",
        "class": "Warrior",
        "faction": "Walled Kingdoms",
        "traits": [
            "Eager",
            "Hulking"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "health": 65,
        "damage": 10,
        "armor": 65,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Tokon",
        "img": "Tokon.webp",
        "name": "Tokon",
        "rarity": "Common",
        "affinity": "Blue",
        "class": "Warrior",
        "faction": "Reefkin",
        "traits": [
            "Polearm",
            "Amphibious"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "health": 60,
        "damage": 11,
        "armor": 46,
        "slot1": "Weapon",
        "slot2": "Shield",
        "slot3": "Amulet"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Umanu",
        "img": "Umanu.webp",
        "name": "Umanu",
        "rarity": "Common",
        "affinity": "Dark",
        "class": "Rogue",
        "faction": "Cavern Realm",
        "traits": [
            "Night Vision",
            "Ranged"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 2,
        "movement": 3,
        "health": 38,
        "damage": 15,
        "armor": 10,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Vittoria",
        "img": "Vittoria.webp",
        "name": "Vittoria",
        "rarity": "Common",
        "affinity": "Light",
        "class": "Warrior",
        "faction": "Fiveport",
        "traits": [
            "Inebriated",
            "Looter"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 3,
        "health": 50,
        "damage": 15,
        "armor": 40,
        "slot1": "Weapon",
        "slot2": "Weapon",
        "slot3": "Ring"
    },
    {
        "link": "https://rivengard.fandom.com/wiki/Voyassa",
        "img": "Voyassa.webp",
        "name": "Voyassa",
        "rarity": "Common",
        "affinity": "Dark",
        "class": "Warrior",
        "faction": "Cavern Realm",
        "traits": [
            "Night Vision",
            "Mounted"
        ],
        "damage_type": "Physical",
        "armor_type": "Physical",
        "range": 1,
        "movement": 4,
        "health": 60,
        "damage": 11,
        "armor": 35,
        "slot1": "Weapon",
        "slot2": "Armor",
        "slot3": "Ring"
    }
]